### ISSUE TITLE
Nothing printed to console with logger 0.9.3

### ISSUE THREAD

**Issue by shimaatech** [leisim/logger#63] opened 2020-09-26 00:33 UTC
Nothing is printed to the console with logger 0.9.3.
it works with 0.9.2

**Comment by ash2osh** [comment] 2020-09-26 12:32
same problem here

**Comment by haarts** [comment] 2020-09-26 13:18
I'll look into it first thing Monday.

**Comment by gksrb4** [comment] 2020-09-28 00:59
> same problem here

1++
Exception has occurred.
FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))

**Comment by phuongphally** [comment] 2020-09-28 05:41
same problem here

**Comment by dev-juyoung** [comment] 2020-09-28 06:32
same problem here

**Comment by haarts** [comment] 2020-09-28 07:06
What exactly are you using? Just a plain `Logger().e('some message')`?

**Comment by haarts** [comment] 2020-09-28 07:56
The issue is fixed in master by reverting the offending commit. I'm releasing soon.

**Closed by haarts** 2020-09-28 07:56 UTC

**Comment by haarts** [comment] 2020-09-28 08:51
> > same problem here
> 
> 1++
> 
> ```
> Exception has occurred.
> FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))
> ```

Is is a different issue I think. I'm guessing you're using the MultiOutput?

**Comment by gksrb4** [comment] 2020-09-28 09:58
> > > same problem here
> > 
> > 
> > 1++
> > ```
> > Exception has occurred.
> > FileSystemException (FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5))
> > ```
> 
> Is is a different issue I think. I'm guessing you're using the MultiOutput?

what is multiouput?

It worked well before upgrade module. 
so, I currently downgrade 0.9.2 and then It works well.
