### ISSUE TITLE
color not working in android studio and noise value

### ISSUE THREAD

**Issue by tbm98** [leisim/logger#3] opened 2019-07-06 15:57 UTC
![Screenshot-20190706225532-1451x1023](https://user-images.githubusercontent.com/52562340/60758482-69cef500-a041-11e9-9d70-1bd0df59fdd8.png)

**Comment by tbm98** [comment] 2019-07-06 16:07
value is exactly when i set colors is false in PrettyPrinter but color still not working :)

**Comment by howardwkim** [comment] 2019-07-07 16:52
Appears to be a known bug #1

I set `colors` to false to remove the extra output and to stop truncation (my logs had `<...>` all over the place).
I turned on `printEmojis` for visual cues.
Still better than the stock logging solution I was using.

**Comment by leisim** [comment] 2019-07-11 15:29
I'm currently fixing this...

**Comment by haarts** [comment] 2019-12-04 14:34
Duplicate of #2

**Closed by haarts** 2019-12-04 14:34 UTC
